language: python
python:
  - "2.7"
install:
 - "pip install -r requirements.txt"
 - "pip install python-coveralls"
script:
 - nosetests  --with-coverage --exclude=app.py  --cover-package=models,database
after_success:
    - coveralls


