language: python
python:
  - "2.7"
instal:
 - "pip install -r requirements.txt"
 - "pip install python-coveralls"
script:
 - python -m nose --with-coverage --cover-package=app
 - coveralls
after-success: coveralls


